import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {localApi} from './local-api';
import './style.css';
import './calendar.css';
import './modal.css';
import './forms.css';
import './home.css';
import './mobile-fit.css';

type Tool={id:string;name:string;internal_number:string;daily_rate:number;default_deposit:number;status:string;brand?:string;model?:string}; type Rental={id:string;full_name:string;tools:string[];tool_ids:string[];issue_date:string;planned_return_date:string;final_rental_amount:number;status:string}; type Booking={id:string;full_name:string;tools:string[];tool_ids?:string[];start_date:string;planned_return_date:string;status:string};
const money=(n:number)=>new Intl.NumberFormat('ru-RU').format(n)+' ₽'; const date=(d:string)=>new Date(d+'T00:00:00').toLocaleDateString('ru-RU');
async function api<T>(url:string,options?:RequestInit):Promise<T>{return localApi<T>(url,options)}
function Status({value}:{value:string}){const labels:Record<string,string>={available:'Доступен',reserved:'Забронирован',rented:'В аренде',service:'На обслуживании',written_off:'Списан',active:'Активна',completed:'Завершена'};return <span className="chip">{labels[value]??value}</span>}
function App(){const [tab,setTab]=useState<'home'|'tools'|'rentals'|'calendar'>('home');const [dashboard,setDashboard]=useState<any>();const [tools,setTools]=useState<Tool[]>([]);const [rentals,setRentals]=useState<Rental[]>([]);const [bookings,setBookings]=useState<Booking[]>([]);const [query,setQuery]=useState('');const [modal,setModal]=useState<null|'tool'|'rental'|'booking'>(null);const [notice,setNotice]=useState('');const refresh=async()=>{try{const [d,t,r,b]=await Promise.all([api<any>('/api/dashboard'),api<Tool[]>('/api/tools?q='+encodeURIComponent(query)),api<Rental[]>('/api/rentals'),api<Booking[]>('/api/bookings')]);setDashboard(d);setTools(t);setRentals(r);setBookings(b)}catch(e){setNotice((e as Error).message)}};useEffect(()=>{refresh()},[query]);const content=useMemo(()=>{if(tab==='home')return <Home d={dashboard} openRental={()=>setModal('rental')}/>;if(tab==='tools')return <Tools tools={tools} query={query} setQuery={setQuery} add={()=>setModal('tool')}/>;if(tab==='rentals')return <Rentals rentals={rentals} booking={()=>setModal('booking')} rental={()=>setModal('rental')}/>;return <Calendar rentals={rentals} bookings={bookings}/>},[tab,dashboard,tools,rentals,bookings,query]);const save=async(url:string,body:any)=>{try{await api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setModal(null);setNotice('Сохранено');refresh()}catch(e){setNotice((e as Error).message)}};return <main><header><div><p className="eyebrow">Аренда инструмента</p><h1>{tab==='home'?'Сегодня':tab==='tools'?'Инструменты':tab==='rentals'?'Аренды':'Календарь'}</h1></div></header>{notice&&<button className="notice" onClick={()=>setNotice('')}>{notice} ×</button>}<section className="content">{content}</section>{tab==='home'&&<button className="primary floating" onClick={()=>setModal('rental')}>+ Новая аренда</button>}<nav>{[['home','⌂','Главная'],['tools','⌕','Инструменты'],['rentals','▣','Аренды'],['calendar','□','Календарь']].map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as any)}><b>{icon}</b>{label}</button>)}</nav>{modal==='tool'&&<ToolForm close={()=>setModal(null)} save={save}/>} {modal==='rental'&&<RentalForm tools={tools} close={()=>setModal(null)} save={save}/>} {modal==='booking'&&<BookingForm tools={tools} close={()=>setModal(null)} save={save}/>}</main>}
function Home({d,openRental}:{d:any;openRental:()=>void}){if(!d)return <p>Загружаем текущую работу…</p>;const reminders=[['Просрочено',d.counters.overdue],['Вернут сегодня',d.counters.due_today],['Выдачи сегодня',d.counters.pickup_today]].filter(([,count])=>count>0);return <><h2 className="home-title">Текущие аренды</h2>{d.rentals.length?d.rentals.map((r:Rental)=><RentalCard key={r.id} r={r}/>):<Empty text="Сейчас нет активных аренд" action="Оформить аренду" onClick={openRental}/>} {reminders.length>0&&<section className="today-summary"><p>На сегодня</p>{reminders.map(([label,count])=><div key={String(label)}><span>{label}</span><b>{count}</b></div>)}</section>}</>}
function Tools({tools,query,setQuery,add}:{tools:Tool[];query:string;setQuery:(x:string)=>void;add:()=>void}){return <><div className="row"><input placeholder="Поиск по названию" value={query} onChange={e=>setQuery(e.target.value)}/><button className="circle" onClick={add}>+</button></div>{tools.length?tools.map(t=><article className="list tool-list" key={t.id}><div className="tool-icon">⚒</div><div className="tool-copy"><b>{t.name}</b>{t.brand&&<small>{t.brand}</small>}</div><div className="tool-meta"><Status value={t.status}/><small>{money(t.daily_rate)}/сут.</small></div></article>):<Empty text="Инструменты ещё не добавлены" action="Добавить инструмент" onClick={add}/>}</>}
function Rentals({rentals,booking,rental}:{rentals:Rental[];booking:()=>void;rental:()=>void}){return <><div className="row"><button className="secondary" onClick={booking}>+ Бронирование</button><button className="primary mini" onClick={rental}>Новая аренда</button></div>{rentals.length?rentals.map(r=><RentalCard key={r.id} r={r}/>):<Empty text="Здесь появится история выдач и возвратов" action="Оформить аренду" onClick={rental}/>}</>}
function RentalCard({r}:{r:Rental}){const finish=async()=>{if(!window.confirm(`Закрыть аренду для «${r.full_name}» и вернуть инструмент в доступные?`))return;try{await api(`/api/rentals/${r.id}/return`,{method:'POST'});window.location.reload()}catch(e){alert((e as Error).message)}};return <article className="card"><div className="between"><b>{r.full_name}</b><Status value={r.status}/></div><p>{r.tools.join(', ')}</p><div className="between muted"><span>{date(r.issue_date)} — {date(r.planned_return_date)}</span><b>{money(r.final_rental_amount)}</b></div>{r.status==='active'&&<button className="secondary return-rental" onClick={finish}>Оформить возврат</button>}</article>}
function Calendar({rentals,bookings}:{rentals:Rental[];bookings:Booking[]}){const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const year=month.getFullYear(),index=month.getMonth(),daysInMonth=new Date(year,index+1,0).getDate(),offset=(new Date(year,index,1).getDay()+6)%7;const iso=(day:number)=>`${year}-${String(index+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const events=[...rentals.map(r=>({id:r.id,name:r.tools.join(', '),start:r.issue_date,end:r.planned_return_date,kind:'rental'})),...bookings.filter(b=>b.status==='active').map(b=>({id:b.id,name:b.tools.join(', '),start:b.start_date,end:b.planned_return_date,kind:'booking'}))];return <><div className="calendar-title"><button className="circle" aria-label="Предыдущий месяц" onClick={()=>setMonth(new Date(year,index-1,1))}>‹</button><h2>{month.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}</h2><button className="circle" aria-label="Следующий месяц" onClick={()=>setMonth(new Date(year,index+1,1))}>›</button></div><div className="weekdays">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=><b key={x}>{x}</b>)}</div><div className="calendar">{Array.from({length:offset},(_,i)=><div className="outside" key={`e${i}`}/>)}{Array.from({length:daysInMonth},(_,i)=>{const day=i+1,value=iso(day),entries=events.filter(e=>e.start<=value&&e.end>=value);return <div key={day} className={value===new Date().toISOString().slice(0,10)?'today':''}><b>{day}</b>{entries.slice(0,2).map(e=><small className={e.kind} key={`${e.id}-${day}`}>{e.name}</small>)}{entries.length>2&&<small>+{entries.length-2}</small>}</div>})}</div><p className="legend"><span className="rental">Аренда</span><span className="booking">Бронирование</span></p></>}
function Empty({text,action,onClick}:{text:string;action:string;onClick:()=>void}){return <div className="empty"><p>{text}</p><button className="secondary" onClick={onClick}>{action}</button></div>}
function Sheet({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){return <div className="overlay"><section className="sheet"><div className="between"><h2>{title}</h2><button className="close" onClick={close}>×</button></div>{children}</section></div>}
function ToolForm({close,save}:{close:()=>void;save:(u:string,b:any)=>void}){const [f,setF]=useState<any>({name:'',internal_number:`tool-${Date.now()}`,purchase_cost:0,daily_rate:0,default_deposit:0,components:[]});return <Sheet title="Новый инструмент" close={close}><form className="tool-form" onSubmit={e=>e.preventDefault()}><Form f={f} setF={setF} fields={[['name','Название'],['purchase_cost','Стоимость покупки'],['daily_rate','Цена за сутки'],['default_deposit','Стандартный залог']]}/><button type="button" className="primary" onClick={()=>save('/api/tools',f)}>Сохранить</button></form></Sheet>}
function RentalForm({tools,close,save}:{tools:Tool[];close:()=>void;save:(u:string,b:any)=>void}){
  const [step,setStep]=useState(1);const [f,setF]=useState<any>({client_id:'',tool_ids:[],issue_date:new Date().toISOString().slice(0,10),planned_return_date:new Date().toISOString().slice(0,10),payment_received_amount:0});const [clients,setClients]=useState<any[]>([]);const [rentals,setRentals]=useState<Rental[]>([]);const [bookings,setBookings]=useState<Booking[]>([]);const [newClient,setNewClient]=useState({full_name:'',phone:''});
  useEffect(()=>{api<any[]>('/api/clients').then(setClients).catch(()=>{});Promise.all([api<Rental[]>('/api/rentals'),api<Booking[]>('/api/bookings')]).then(([r,b])=>{setRentals(r);setBookings(b)}).catch(()=>{})},[]);
  const overlaps=(start:string,end:string,otherStart:string,otherEnd:string)=>start<=otherEnd&&otherStart<=end;
  const blocked=(tool:Tool)=>rentals.some(r=>r.status==='active'&&r.tool_ids.includes(tool.id)&&overlaps(f.issue_date,f.planned_return_date,r.issue_date,r.planned_return_date))||bookings.some(b=>b.status==='active'&&(b.tool_ids?.includes(tool.id)||(!b.tool_ids&&b.tools.includes(tool.name)))&&overlaps(f.issue_date,f.planned_return_date,b.start_date,b.planned_return_date));
  const available=tools.filter(t=>t.status!=='service'&&t.status!=='written_off'&&!blocked(t));
  const addClient=async()=>{try{const c=await api<any>('/api/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(newClient)});setClients([...clients,c]);setF({...f,client_id:c.id});setNewClient({full_name:'',phone:''})}catch(e){alert((e as Error).message)}};
  return <Sheet title={`Новая аренда · ${step}/4`} close={close}>{step===1&&<><p className="muted">Выберите клиента или добавьте нового прямо здесь.</p><label>Клиент<select value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})}><option value="">Выберите клиента</option>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.phone}</option>)}</select></label><div className="new-client"><b>Новый клиент</b><input placeholder="Имя" value={newClient.full_name} onChange={e=>setNewClient({...newClient,full_name:e.target.value})}/><input inputMode="tel" placeholder="Телефон" value={newClient.phone} onChange={e=>setNewClient({...newClient,phone:e.target.value})}/><button type="button" className="secondary" disabled={!newClient.full_name||!newClient.phone} onClick={addClient}>Добавить клиента</button></div></>}{step===2&&<><p className="muted">Сначала укажите период: список инструментов на следующем шаге покажет доступность именно для этих дат.</p><Form f={f} setF={setF} fields={[['issue_date','Дата выдачи','date'],['planned_return_date','Дата возврата','date'],['final_rental_amount','Итоговая сумма (необязательно)']]} /></>}{step===3&&<>{available.length?available.map(t=><label className="check" key={t.id}><input type="checkbox" checked={f.tool_ids.includes(t.id)} onChange={()=>setF({...f,tool_ids:f.tool_ids.includes(t.id)?f.tool_ids.filter((x:string)=>x!==t.id):[...f.tool_ids,t.id]})}/>{t.name} · {money(t.daily_rate)}/сут.</label>):<p className="empty-inline">На выбранные даты нет свободных инструментов.</p>}</>}{step===4&&<><p>Клиент: {clients.find(c=>c.id===f.client_id)?.full_name||'не выбран'}</p><p>Период: {date(f.issue_date)} — {date(f.planned_return_date)}</p><p>Инструментов: {f.tool_ids.length}</p><p>Проверьте данные и подтвердите выдачу.</p></>}<div className="row bottom">{step>1&&<button className="secondary" onClick={()=>setStep(step-1)}>Назад</button>}{step<4?<button className="primary" disabled={step===1?!f.client_id:step===2?!f.issue_date||!f.planned_return_date:false} onClick={()=>setStep(step+1)}>Далее</button>:<button className="primary" disabled={!f.client_id||!f.tool_ids.length} onClick={()=>save('/api/rentals',f)}>Выдать</button>}</div></Sheet>}
function BookingForm({tools,close,save}:{tools:Tool[];close:()=>void;save:(u:string,b:any)=>void}){
  const [clients,setClients]=useState<any[]>([]);const [rentals,setRentals]=useState<Rental[]>([]);const [bookings,setBookings]=useState<Booking[]>([]);
  const [f,setF]=useState<any>({client_id:'',tool_ids:[],start_date:new Date().toISOString().slice(0,10),planned_return_date:new Date().toISOString().slice(0,10),comment:''});const [newClient,setNewClient]=useState({full_name:'',phone:''});
  useEffect(()=>{api<any[]>('/api/clients').then(setClients).catch(()=>{});Promise.all([api<Rental[]>('/api/rentals'),api<Booking[]>('/api/bookings')]).then(([r,b])=>{setRentals(r);setBookings(b)}).catch(()=>{})},[]);
  const overlaps=(start:string,end:string,otherStart:string,otherEnd:string)=>start<=otherEnd&&otherStart<=end;
  const blocked=(tool:Tool)=>rentals.some(r=>r.status==='active'&&r.tool_ids.includes(tool.id)&&overlaps(f.start_date,f.planned_return_date,r.issue_date,r.planned_return_date))||bookings.some(b=>b.status==='active'&&(b.tool_ids?.includes(tool.id)||(!b.tool_ids&&b.tools.includes(tool.name)))&&overlaps(f.start_date,f.planned_return_date,b.start_date,b.planned_return_date));
  const available=tools.filter(t=>t.status!=='service'&&t.status!=='written_off'&&!blocked(t));
  const addClient=async()=>{try{const c=await api<any>('/api/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(newClient)});setClients([...clients,c]);setF({...f,client_id:c.id});setNewClient({full_name:'',phone:''})}catch(e){alert((e as Error).message)}};
  return <Sheet title="Новое бронирование" close={close}><p className="muted">Выберите клиента, период и свободный на эти даты инструмент.</p><h3 className="form-section">Клиент</h3><label>Клиент<select value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})}><option value="">Выберите клиента</option>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.phone}</option>)}</select></label><div className="new-client"><b>Новый клиент</b><input placeholder="Имя" value={newClient.full_name} onChange={e=>setNewClient({...newClient,full_name:e.target.value})}/><input inputMode="tel" placeholder="Телефон" value={newClient.phone} onChange={e=>setNewClient({...newClient,phone:e.target.value})}/><button type="button" className="secondary" disabled={!newClient.full_name||!newClient.phone} onClick={addClient}>Добавить клиента</button></div><h3 className="form-section">Период</h3><Form f={f} setF={setF} fields={[["start_date","Дата начала","date"],["planned_return_date","Дата возврата","date"],["comment","Комментарий"]]}/><h3 className="form-section">Инструменты для резерва</h3>{available.length?available.map(t=><label className="check tool-choice" key={t.id}><input type="checkbox" checked={f.tool_ids.includes(t.id)} onChange={()=>setF({...f,tool_ids:f.tool_ids.includes(t.id)?f.tool_ids.filter((x:string)=>x!==t.id):[...f.tool_ids,t.id]})}/><span><b>{t.name}</b><small>{money(t.daily_rate)}/сут.</small></span></label>):<p className="empty-inline">На этот период нет свободных инструментов.</p>}<p className="selected-count">Выбрано инструментов: {f.tool_ids.length}</p><button className="primary" disabled={!f.client_id||!f.tool_ids.length} onClick={()=>save('/api/bookings',f)}>Забронировать</button></Sheet>}
function Form({f,setF,fields}:{f:any;setF:(v:any)=>void;fields:string[][]}){return <>{fields.map(([key,label,type])=>{const numeric=type??(key.includes('cost')||key.includes('rate')||key.includes('amount')||key.includes('deposit')?'number':'text');return <label key={key}>{label}<input type={numeric} inputMode={numeric==='number'?'numeric':undefined} value={f[key]??''} onFocus={e=>{if(numeric==='number'&&Number(e.currentTarget.value)===0)e.currentTarget.select()}} onChange={e=>setF({...f,[key]:e.target.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value})}/></label>})}</>}
createRoot(document.getElementById('root')!).render(<App/>);
