import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {cached,queue,sync} from './offline';
import './style.css';

type Tool={id:string;name:string;internal_number:string;daily_rate:number;default_deposit:number;status:string;brand?:string;model?:string}; type Rental={id:string;full_name:string;tools:string[];issue_date:string;planned_return_date:string;final_rental_amount:number;status:string};
const money=(n:number)=>new Intl.NumberFormat('ru-RU').format(n)+' ₽'; const date=(d:string)=>new Date(d+'T00:00:00').toLocaleDateString('ru-RU');
async function api<T>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,options);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).message??'Ошибка сохранения');return r.json();}
function Status({value}:{value:string}){const labels:Record<string,string>={available:'Доступен',reserved:'Забронирован',rented:'В аренде',service:'На обслуживании',written_off:'Списан',active:'Активна',completed:'Завершена'};return <span className="chip">{labels[value]??value}</span>}
function App(){const [tab,setTab]=useState<'home'|'tools'|'rentals'|'calendar'>('home');const [online,setOnline]=useState(navigator.onLine);const [dashboard,setDashboard]=useState<any>();const [tools,setTools]=useState<Tool[]>([]);const [rentals,setRentals]=useState<Rental[]>([]);const [query,setQuery]=useState('');const [modal,setModal]=useState<null|'tool'|'rental'|'booking'>(null);const [notice,setNotice]=useState('');const refresh=async()=>{try{const [d,t,r]=await Promise.all([cached<any>('dashboard',()=>api('/api/dashboard')),cached<Tool[]>('tools',()=>api<Tool[]>('/api/tools?q='+encodeURIComponent(query))),cached<Rental[]>('rentals',()=>api<Rental[]>('/api/rentals'))]);setDashboard(d);setTools(t);setRentals(r);await sync();}catch(e){setNotice((e as Error).message)}};useEffect(()=>{refresh();const on=()=>{setOnline(navigator.onLine);if(navigator.onLine)refresh()};addEventListener('online',on);addEventListener('offline',on);return()=>{removeEventListener('online',on);removeEventListener('offline',on)}},[query]);const content=useMemo(()=>{if(tab==='home')return <Home d={dashboard} openRental={()=>setModal('rental')}/>;if(tab==='tools')return <Tools tools={tools} query={query} setQuery={setQuery} add={()=>setModal('tool')}/>;if(tab==='rentals')return <Rentals rentals={rentals} booking={()=>setModal('booking')} rental={()=>setModal('rental')}/>;return <Calendar rentals={rentals}/>},[tab,dashboard,tools,rentals,query]);const save=async(url:string,body:any)=>{try{if(!online){await queue(url,body);setNotice('Нет сети — изменение поставлено в очередь');}else await api(url,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)});setModal(null);setNotice('Все изменения сохранены');refresh();}catch(e){setNotice((e as Error).message)}};return <main><header><div><p className="eyebrow">Аренда инструмента</p><h1>{tab==='home'?'Сегодня':tab==='tools'?'Инструменты':tab==='rentals'?'Аренды':'Календарь'}</h1></div><span className={'sync '+(online?'':'offline')}>{online?'Все изменения сохранены':'Нет сети'}</span></header>{notice&&<button className="notice" onClick={()=>setNotice('')}>{notice} ×</button>}<section className="content">{content}</section>{tab==='home'&&<button className="primary floating" onClick={()=>setModal('rental')}>+ Новая аренда</button>}<nav>{[['home','⌂','Главная'],['tools','⌕','Инструменты'],['rentals','▣','Аренды'],['calendar','□','Календарь']].map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as any)}><b>{icon}</b>{label}</button>)}</nav>{modal==='tool'&&<ToolForm close={()=>setModal(null)} save={save}/>} {modal==='rental'&&<RentalForm tools={tools} close={()=>setModal(null)} save={save}/>} {modal==='booking'&&<BookingForm tools={tools} close={()=>setModal(null)} save={save}/>}</main>}
function Home({d,openRental}:{d:any;openRental:()=>void}){if(!d)return <p>Загружаем текущую работу…</p>;return <><div className="metrics"><button>Просрочено <b>{d.counters.overdue}</b></button><button>Вернуть сегодня <b>{d.counters.due_today}</b></button><button>Заберут сегодня <b>{d.counters.pickup_today}</b></button></div><h2>Текущие аренды</h2>{d.rentals.length?d.rentals.map((r:Rental)=><RentalCard key={r.id} r={r}/>):<Empty text="Сейчас нет активных аренд" action="Оформить аренду" onClick={openRental}/>}</>}
function Tools({tools,query,setQuery,add}:{tools:Tool[];query:string;setQuery:(x:string)=>void;add:()=>void}){return <><div className="row"><input placeholder="Поиск по названию или номеру" value={query} onChange={e=>setQuery(e.target.value)}/><button className="circle" onClick={add}>+</button></div>{tools.length?tools.map(t=><article className="list" key={t.id}><div className="tool-icon">⚒</div><div><b>{t.name}</b><small>№ {t.internal_number}{t.brand?' · '+t.brand:''}</small></div><div><Status value={t.status}/><small>{money(t.daily_rate)}/сут.</small></div></article>):<Empty text="Инструменты ещё не добавлены" action="Добавить инструмент" onClick={add}/>}</>}
function Rentals({rentals,booking,rental}:{rentals:Rental[];booking:()=>void;rental:()=>void}){return <><div className="row"><button className="secondary" onClick={booking}>+ Бронирование</button><button className="primary mini" onClick={rental}>Новая аренда</button></div>{rentals.length?rentals.map(r=><RentalCard key={r.id} r={r}/>):<Empty text="Здесь появится история выдач и возвратов" action="Оформить аренду" onClick={rental}/>}</>}
function RentalCard({r}:{r:Rental}){return <article className="card"><div className="between"><b>{r.full_name}</b><Status value={r.status}/></div><p>{r.tools.join(', ')}</p><div className="between muted"><span>{date(r.issue_date)} — {date(r.planned_return_date)}</span><b>{money(r.final_rental_amount)}</b></div></article>}
function Calendar({rentals}:{rentals:Rental[]}){return <><p className="muted">Периоды аренд и бронирований</p><div className="calendar">{Array.from({length:31},(_,i)=><div key={i}><b>{i+1}</b>{rentals.filter(r=>r.issue_date.slice(-2)===String(i+1).padStart(2,'0')).slice(0,2).map(r=><small key={r.id}>{r.full_name}</small>)}</div>)}</div></>}
function Empty({text,action,onClick}:{text:string;action:string;onClick:()=>void}){return <div className="empty"><p>{text}</p><button className="secondary" onClick={onClick}>{action}</button></div>}
function Sheet({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){return <div className="overlay"><section className="sheet"><div className="between"><h2>{title}</h2><button className="close" onClick={close}>×</button></div>{children}</section></div>}
function ToolForm({close,save}:{close:()=>void;save:(u:string,b:any)=>void}){const [f,setF]=useState<any>({name:'',internal_number:'',purchase_cost:0,daily_rate:0,default_deposit:0,components:[]});return <Sheet title="Новый инструмент" close={close}><Form f={f} setF={setF} fields={[['name','Название'],['internal_number','Внутренний номер'],['purchase_cost','Стоимость покупки'],['daily_rate','Цена за сутки'],['default_deposit','Стандартный залог']]}/><button className="primary" onClick={()=>save('/api/tools',f)}>Сохранить</button></Sheet>}
function RentalForm({tools,close,save}:{tools:Tool[];close:()=>void;save:(u:string,b:any)=>void}){const [step,setStep]=useState(1);const [f,setF]=useState<any>({client_id:'',tool_ids:[],issue_date:new Date().toISOString().slice(0,10),planned_return_date:new Date().toISOString().slice(0,10),payment_received_amount:0});const [clients,setClients]=useState<any[]>([]);useEffect(()=>{api<any[]>('/api/clients').then(setClients).catch(()=>{})},[]);return <Sheet title={`Новая аренда · ${step}/4`} close={close}>{step===1&&<><p className="muted">Выберите клиента. Если клиента нет, добавьте его через API или карточку клиента.</p><select value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})}><option value="">Выберите клиента</option>{clients.map(c=><option value={c.id}>{c.full_name} · {c.phone}</option>)}</select></>}{step===2&&<>{tools.filter(t=>t.status==='available').map(t=><label className="check"><input type="checkbox" checked={f.tool_ids.includes(t.id)} onChange={()=>setF({...f,tool_ids:f.tool_ids.includes(t.id)?f.tool_ids.filter((x:string)=>x!==t.id):[...f.tool_ids,t.id]})}/>{t.name} · {money(t.daily_rate)}/сут.</label>)}</>}{step===3&&<Form f={f} setF={setF} fields={[['issue_date','Дата выдачи','date'],['planned_return_date','Дата возврата','date'],['final_rental_amount','Итоговая сумма (необязательно)']]} />}{step===4&&<><p>Клиент: {clients.find(c=>c.id===f.client_id)?.full_name||'не выбран'}</p><p>Инструментов: {f.tool_ids.length}</p><p>Проверьте даты и подтвердите выдачу.</p></>}<div className="row bottom">{step>1&&<button className="secondary" onClick={()=>setStep(step-1)}>Назад</button>}{step<4?<button className="primary" onClick={()=>setStep(step+1)}>Далее</button>:<button className="primary" disabled={!f.client_id||!f.tool_ids.length} onClick={()=>save('/api/rentals',f)}>Выдать</button>}</div></Sheet>}
function BookingForm({tools,close,save}:{tools:Tool[];close:()=>void;save:(u:string,b:any)=>void}){const [clients,setClients]=useState<any[]>([]);const [f,setF]=useState<any>({client_id:'',tool_ids:[],start_date:new Date().toISOString().slice(0,10),planned_return_date:new Date().toISOString().slice(0,10),comment:''});useEffect(()=>{api<any[]>('/api/clients').then(setClients).catch(()=>{})},[]);return <Sheet title="Бронирование" close={close}><p className="muted">Зарезервируйте доступные инструменты под клиента на выбранный период.</p><label>Клиент<select value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})}><option value="">Выберите клиента</option>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.phone}</option>)}</select></label><Form f={f} setF={setF} fields={[["start_date","Дата начала","date"],["planned_return_date","Дата возврата","date"],["comment","Комментарий"]]}/>{tools.filter(t=>t.status==='available').map(t=><label className="check" key={t.id}><input type="checkbox" checked={f.tool_ids.includes(t.id)} onChange={()=>setF({...f,tool_ids:f.tool_ids.includes(t.id)?f.tool_ids.filter((x:string)=>x!==t.id):[...f.tool_ids,t.id]})}/>{t.name} · {money(t.daily_rate)}/сут.</label>)}<button className="primary" disabled={!f.client_id||!f.tool_ids.length} onClick={()=>save('/api/bookings',f)}>Забронировать</button></Sheet>}
function Form({f,setF,fields}:{f:any;setF:(v:any)=>void;fields:string[][]}){return <>{fields.map(([key,label,type])=><label key={key}>{label}<input type={type??(key.includes('cost')||key.includes('rate')||key.includes('amount')||key.includes('deposit')?'number':'text')} value={f[key]??''} onChange={e=>setF({...f,[key]:e.target.type==='number'?Number(e.target.value):e.target.value})}/></label>)}</>}
createRoot(document.getElementById('root')!).render(<App/>);
