import Fastify from 'fastify';
import cors from '@fastify/cors';
import pg from 'pg';
import { z } from 'zod';

const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const app = Fastify({ logger: true });
await app.register(cors, { origin: true });

const money = z.coerce.number().int().min(0);
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const toolInput = z.object({ name: z.string().min(1), category: z.string().optional(), brand: z.string().optional(), model: z.string().optional(), internal_number: z.string().min(1), photo_url: z.string().url().optional().or(z.literal('')), purchase_date: date.optional().or(z.literal('')), purchase_cost: money, daily_rate: money, default_deposit: money, description: z.string().optional(), components: z.array(z.string().min(1)).default([]) });
const clientInput = z.object({ full_name: z.string().min(1), phone: z.string().min(1), document_details: z.string().optional(), address: z.string().optional(), comment: z.string().optional() });
const period = z.object({ start_date: date, planned_return_date: date }).refine(v => v.planned_return_date >= v.start_date, { message: 'Дата возврата не может быть раньше даты выдачи' });

type Db = pg.PoolClient;
const fail = (status: number, message: string) => Object.assign(new Error(message), { statusCode: status });
const days = (start: string, end: string) => Math.max(1, Math.round((Date.parse(`${end}T00:00:00Z`) - Date.parse(`${start}T00:00:00Z`)) / 86400000));
const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'Europe/Samara' });
async function transaction<T>(fn: (db: Db) => Promise<T>) { const db = await pool.connect(); try { await db.query('BEGIN'); const result = await fn(db); await db.query('COMMIT'); return result; } catch (e) { await db.query('ROLLBACK'); throw e; } finally { db.release(); } }
async function conflict(db: Db, toolIds: string[], start: string, end: string, excludeBooking?: string, excludeRental?: string) {
  const result = await db.query(`SELECT t.name FROM tools t WHERE t.id = ANY($1) AND (EXISTS (SELECT 1 FROM rental_items ri JOIN rentals r ON r.id=ri.rental_id WHERE ri.tool_id=t.id AND r.status='active' AND ($4::uuid IS NULL OR r.id <> $4::uuid) AND daterange(r.issue_date,r.planned_return_date,'[]') && daterange($2::date,$3::date,'[]')) OR EXISTS (SELECT 1 FROM booking_items bi JOIN bookings b ON b.id=bi.booking_id WHERE bi.tool_id=t.id AND b.status='active' AND ($5::uuid IS NULL OR b.id <> $5::uuid) AND daterange(b.start_date,b.planned_return_date,'[]') && daterange($2::date,$3::date,'[]')))` , [toolIds, start, end, excludeRental ?? null, excludeBooking ?? null]);
  if (result.rowCount) throw fail(409, `Инструмент уже занят на выбранный период: ${result.rows.map(x => x.name).join(', ')}`);
}
async function stored(db: Db, key: string | undefined) { if (!key) return null; const r = await db.query('SELECT response FROM idempotency_keys WHERE key=$1', [key]); return r.rows[0]?.response ?? null; }
async function remember(db: Db, key: string | undefined, response: unknown) { if (key) await db.query('INSERT INTO idempotency_keys(key,response) VALUES($1,$2)', [key, response]); return response; }

app.get('/health', async () => ({ ok: true }));
app.get('/api/dashboard', async () => { const d = today(); const [rentals, counters] = await Promise.all([pool.query(`SELECT r.*, c.full_name, array_agg(t.name ORDER BY t.name) tools FROM rentals r JOIN clients c ON c.id=r.client_id JOIN rental_items ri ON ri.rental_id=r.id JOIN tools t ON t.id=ri.tool_id WHERE r.status='active' GROUP BY r.id,c.full_name ORDER BY (r.planned_return_date < $1) DESC,r.planned_return_date`, [d]), pool.query(`SELECT (SELECT count(*) FROM rentals WHERE status='active' AND planned_return_date < $1)::int overdue, (SELECT count(*) FROM rentals WHERE status='active' AND planned_return_date=$1)::int due_today, (SELECT count(*) FROM bookings WHERE status='active' AND start_date=$1)::int pickup_today`, [d])]); return { today: d, counters: counters.rows[0], rentals: rentals.rows }; });
app.get('/api/tools', async (req) => { const q = (req.query as { q?: string }).q?.trim() ?? ''; const r = await pool.query(`SELECT * FROM tools WHERE $1='' OR concat_ws(' ',name,brand,model,internal_number) ILIKE '%' || $1 || '%' ORDER BY name`, [q]); return r.rows; });
app.post('/api/tools', async (req, reply) => { const input = toolInput.parse(req.body); const result = await transaction(async db => { const t = await db.query(`INSERT INTO tools(name,category,brand,model,internal_number,photo_url,purchase_date,purchase_cost,daily_rate,default_deposit,description) VALUES($1,$2,$3,$4,$5,NULLIF($6,''),NULLIF($7,'')::date,$8,$9,$10,$11) RETURNING *`, [input.name,input.category,input.brand,input.model,input.internal_number,input.photo_url ?? '',input.purchase_date ?? '',input.purchase_cost,input.daily_rate,input.default_deposit,input.description]); for (let i=0;i<input.components.length;i++) await db.query('INSERT INTO tool_components(tool_id,name,sort_order) VALUES($1,$2,$3)', [t.rows[0].id,input.components[i],i]); return t.rows[0]; }); reply.code(201); return result; });
app.get('/api/tools/:id', async (req) => { const id=(req.params as {id:string}).id; const [tool,components,expenses,history] = await Promise.all([pool.query('SELECT * FROM tools WHERE id=$1',[id]),pool.query('SELECT * FROM tool_components WHERE tool_id=$1 AND active ORDER BY sort_order',[id]),pool.query('SELECT * FROM maintenance_expenses WHERE tool_id=$1 ORDER BY expense_date DESC',[id]),pool.query(`SELECT r.*,c.full_name FROM rentals r JOIN rental_items ri ON ri.rental_id=r.id JOIN clients c ON c.id=r.client_id WHERE ri.tool_id=$1 ORDER BY r.issue_date DESC`,[id])]); if(!tool.rowCount) throw fail(404,'Инструмент не найден'); const income=await pool.query(`SELECT coalesce(sum(ri.income_amount),0)::int amount FROM rental_items ri JOIN rentals r ON r.id=ri.rental_id WHERE ri.tool_id=$1 AND r.status='completed'`,[id]); const costs=expenses.rows.reduce((s,e)=>s+e.amount,0); const net=income.rows[0].amount-tool.rows[0].purchase_cost-costs; return {...tool.rows[0],components:components.rows,expenses:expenses.rows,history:history.rows,profitability:{income:income.rows[0].amount,expenses:costs,net}}; });
app.post('/api/clients', async (req, reply) => { const input=clientInput.parse(req.body); const r=await pool.query('INSERT INTO clients(full_name,phone,document_details,address,comment) VALUES($1,$2,$3,$4,$5) RETURNING *',[input.full_name,input.phone,input.document_details,input.address,input.comment]); reply.code(201); return r.rows[0]; });
app.get('/api/clients', async (req) => { const q=(req.query as {q?:string}).q ?? ''; const r=await pool.query(`SELECT * FROM clients WHERE concat_ws(' ',full_name,phone) ILIKE '%'||$1||'%' ORDER BY full_name`,[q]); return r.rows; });
app.post('/api/bookings', async (req, reply) => { const body=z.object({client_id:z.string().uuid(),tool_ids:z.array(z.string().uuid()).min(1),comment:z.string().optional()}).and(period).parse(req.body); if(new Set(body.tool_ids).size!==body.tool_ids.length) throw fail(400,'Инструмент нельзя добавить дважды'); const result=await transaction(async db=>{await conflict(db,body.tool_ids,body.start_date,body.planned_return_date); const tools=await db.query('SELECT id,daily_rate,default_deposit,status FROM tools WHERE id=ANY($1) FOR UPDATE',[body.tool_ids]); if(tools.rowCount!==body.tool_ids.length || tools.rows.some(t=>t.status!=='available')) throw fail(409,'Выберите только доступные инструменты'); const b=await db.query('INSERT INTO bookings(client_id,start_date,planned_return_date,comment) VALUES($1,$2,$3,$4) RETURNING *',[body.client_id,body.start_date,body.planned_return_date,body.comment]); for(const t of tools.rows) await db.query('INSERT INTO booking_items(booking_id,tool_id,daily_rate_snapshot,deposit_snapshot) VALUES($1,$2,$3,$4)',[b.rows[0].id,t.id,t.daily_rate,t.default_deposit]); await db.query("UPDATE tools SET status='reserved',updated_at=now() WHERE id=ANY($1)",[body.tool_ids]); return b.rows[0]; }); reply.code(201); return result; });
app.get('/api/bookings', async ()=> (await pool.query(`SELECT b.*,c.full_name,array_agg(t.name) tools FROM bookings b JOIN clients c ON c.id=b.client_id JOIN booking_items bi ON bi.booking_id=b.id JOIN tools t ON t.id=bi.tool_id GROUP BY b.id,c.full_name ORDER BY b.start_date DESC`)).rows);
app.post('/api/rentals', async (req, reply) => { const key=req.headers['idempotency-key'] as string|undefined; const body=z.object({client_id:z.string().uuid(),booking_id:z.string().uuid().optional(),tool_ids:z.array(z.string().uuid()).min(1),issue_date:date,planned_return_date:date,final_rental_amount:money.optional(),deposit_received:z.boolean().default(false),payment_received_amount:money.default(0),comment:z.string().optional()}).refine(v=>v.planned_return_date>=v.issue_date,{message:'Некорректный период'}).parse(req.body); const result=await transaction(async db=>{const old=await stored(db,key);if(old)return old;if(new Set(body.tool_ids).size!==body.tool_ids.length)throw fail(400,'Инструмент нельзя добавить дважды'); await conflict(db,body.tool_ids,body.issue_date,body.planned_return_date,body.booking_id); const tools=await db.query('SELECT * FROM tools WHERE id=ANY($1) FOR UPDATE',[body.tool_ids]); if(tools.rowCount!==body.tool_ids.length || tools.rows.some(t=>!['available','reserved'].includes(t.status)))throw fail(409,'Инструмент недоступен'); const n=days(body.issue_date,body.planned_return_date); const calculated=tools.rows.reduce((s,t)=>s+t.daily_rate*n,0); const final=body.final_rental_amount ?? calculated; const deposit=tools.rows.reduce((s,t)=>s+t.default_deposit,0); const rental=await db.query(`INSERT INTO rentals(client_id,booking_id,issue_date,planned_return_date,calculated_amount,final_rental_amount,deposit_amount,deposit_received,payment_received_amount,is_paid,comment) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[body.client_id,body.booking_id,body.issue_date,body.planned_return_date,calculated,final,deposit,body.deposit_received,body.payment_received_amount,body.payment_received_amount>=final,body.comment]); for(const t of tools.rows){const amount=t.daily_rate*n;const income=calculated?Math.round(final*amount/calculated):Math.floor(final/tools.rows.length); await db.query('INSERT INTO rental_items(rental_id,tool_id,daily_rate_snapshot,calculated_amount,income_amount,deposit_snapshot,issued_components) VALUES($1,$2,$3,$4,$5,$6,$7)',[rental.rows[0].id,t.id,t.daily_rate,amount,income,t.default_deposit,JSON.stringify([])]);} await db.query("UPDATE tools SET status='rented',updated_at=now() WHERE id=ANY($1)",[body.tool_ids]); if(body.booking_id)await db.query("UPDATE bookings SET status='converted',updated_at=now() WHERE id=$1",[body.booking_id]); return remember(db,key,rental.rows[0]);}); reply.code(201);return result; });
app.get('/api/rentals', async ()=> (await pool.query(`SELECT r.*,c.full_name,array_agg(t.name ORDER BY t.name) tools FROM rentals r JOIN clients c ON c.id=r.client_id JOIN rental_items ri ON ri.rental_id=r.id JOIN tools t ON t.id=ri.tool_id GROUP BY r.id,c.full_name ORDER BY r.issue_date DESC`)).rows);
app.post('/api/rentals/:id/extend', async req=>{const id=(req.params as {id:string}).id;const body=z.object({planned_return_date:date,final_rental_amount:money.optional()}).parse(req.body);return transaction(async db=>{const r=await db.query('SELECT * FROM rentals WHERE id=$1 FOR UPDATE',[id]);if(!r.rowCount||r.rows[0].status!=='active')throw fail(404,'Активная аренда не найдена');if(body.planned_return_date<r.rows[0].issue_date)throw fail(400,'Некорректная дата');const tools=(await db.query('SELECT tool_id FROM rental_items WHERE rental_id=$1',[id])).rows.map(x=>x.tool_id);await conflict(db,tools,r.rows[0].issue_date,body.planned_return_date,undefined,id);const n=days(r.rows[0].issue_date,body.planned_return_date);const items=await db.query('SELECT * FROM rental_items WHERE rental_id=$1',[id]);const calculated=items.rows.reduce((s,x)=>s+x.daily_rate_snapshot*n,0);await db.query('UPDATE rentals SET planned_return_date=$2,calculated_amount=$3,final_rental_amount=$4,updated_at=now() WHERE id=$1',[id,body.planned_return_date,calculated,body.final_rental_amount??calculated]);return {ok:true};});});
app.post('/api/rentals/:id/return', async req=>{const id=(req.params as {id:string}).id;const key=req.headers['idempotency-key'] as string|undefined;const body=z.object({items:z.array(z.object({tool_id:z.string().uuid(),condition:z.enum(['available','service']),comment:z.string().optional(),components:z.array(z.object({name:z.string(),present:z.boolean()})).default([])})).min(1)}).parse(req.body);return transaction(async db=>{const old=await stored(db,key);if(old)return old;const r=await db.query('SELECT * FROM rentals WHERE id=$1 FOR UPDATE',[id]);if(!r.rowCount||r.rows[0].status!=='active')throw fail(404,'Активная аренда не найдена');const existing=await db.query('SELECT tool_id FROM rental_items WHERE rental_id=$1',[id]);if(existing.rowCount!==body.items.length||body.items.some(i=>!existing.rows.some(x=>x.tool_id===i.tool_id)))throw fail(400,'Нужно проверить каждую позицию аренды');for(const item of body.items){if(item.condition==='service'&&!item.comment)throw fail(400,'Укажите причину обслуживания');await db.query('UPDATE rental_items SET returned_components=$2,return_condition=$3,return_comment=$4 WHERE rental_id=$1 AND tool_id=$5',[id,JSON.stringify(item.components),item.condition,item.comment,item.tool_id]);await db.query("UPDATE tools SET status=$2,service_note=$3,updated_at=now() WHERE id=$1",[item.tool_id,item.condition,item.condition==='service'?item.comment:null]);}await db.query("UPDATE rentals SET status='completed',completed_date=$2,updated_at=now() WHERE id=$1",[id,today()]);return remember(db,key,{ok:true});});});
app.post('/api/tools/:id/expenses', async (req,reply)=>{const id=(req.params as {id:string}).id;const body=z.object({expense_date:date,amount:money,comment:z.string().min(1)}).parse(req.body);const r=await pool.query('INSERT INTO maintenance_expenses(tool_id,expense_date,amount,comment) VALUES($1,$2,$3,$4) RETURNING *',[id,body.expense_date,body.amount,body.comment]);reply.code(201);return r.rows[0];});
app.post('/api/tools/:id/status', async req=>{const id=(req.params as {id:string}).id;const body=z.object({status:z.enum(['available','service','written_off']),service_note:z.string().optional()}).parse(req.body);if(body.status==='service'&&!body.service_note)throw fail(400,'Укажите причину обслуживания');await pool.query('UPDATE tools SET status=$2,service_note=$3,updated_at=now() WHERE id=$1',[id,body.status,body.service_note??null]);return {ok:true};});
app.setErrorHandler((error,_req,reply)=>{const err=error as Error & {statusCode?:number};const status=err.statusCode??(err.name==='ZodError'?400:500);reply.code(status).send({message:err.message||'Внутренняя ошибка'});});
await app.listen({ port:Number(process.env.PORT??3000), host:'0.0.0.0' });
